### ISSUE TITLE
[Suggestion] Oh, how the crafting has tabled, compatability & texture

### ISSUE THREAD

**Issue by milkev** [LordDeatHunter/ColoredCraftingStations#4]
https://www.curseforge.com/minecraft/mc-mods/oh-how-the-crafting-has-tabled 
it would be cool if the mod had compatability with oh how the crafting has tabled, and when you used a certain type of crafting table, the wooden texture on the coloured station would be that texture as well.

**Comment by LordDeatHunter** [comment]
I've been wanting to improve this mod for a while, but nothing really came to mind. Thanks :) Will get to this soon.

**Comment by LordDeatHunter** [comment]
Instead of OHTCHT support, I changed the recipe. Now you can create stations from any plank type, including BYG planks (other mod ideas are welcome).
